version: "3.0"

volumes:
    node-module-volume:

services:
    app:
        build: .
        ports:
            - 80:8080
        volumes:
            - ./src:/app
            - node-module-volume:/app/node_modules
        tty: true
        restart: always
