version: "3.0"

volumes:
    node-module-volume:

services:
    frontend:
        build: ./Frontend
        ports:
            - 80:8080
        volumes:
            - ./Frontend/src:/app
            - node-module-volume:/app/node_modules
        tty: true
        restart: always
        depends_on:
            - backend

    backend:
        build: ./Backend
        ports:
            - 3000:3000
        volumes:
            - ./Backend/src:/app
        depends_on:
            - db

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
